title: BLAHAJ
author: tran
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  What does Blahaj mean? Blahaj means "Blue Shark" in Swedish. 
  The Blahaj has a dark blue colored body, with 2 black eyes, a mouth with teeth, and a white belly.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
